---
- hosts: webservers
  become: true
  become_method: sudo

  tasks:
  - name: Ensure Apache is installed
    yum: name=httpd state=present

  - name: Start Apache Services
    service: name=httpd state=started enabled=yes 

- hosts: dbservers
  become: true
  become_method: sudo

  tasks:
  - name: Ensure MYSQL is installed
    yum: name=mysql-server state=present

  - name: Start MYSQL Services
    service: name=mysqld state=started enabled=yes

- hosts: webservers:dbservers
  become: true
  become_method: sudo

  tasks:
  - name: Stop IP Tables Now
    service: name=iptables state=stopped
